export const FETCH_DETAIL_ARTICLE_REQUEST = "FETCH_DETAIL_ARTICLE_REQUEST";
export const FETCH_DETAIL_ARTICLE_SUCCESS = "FETCH_DETAIL_ARTICLE_SUCCESS";
export const FETCH_DETAIL_ARTICLE_ERRORS = "FETCH_DETAIL_ARTICLE_ERRORS";
export const SET_STATE_DEFAULT = "SET_STATE_DEFAULT";
