export const FETCH_SETTINGS_REQUESTING = "FETCH_SETTINGS_REQUESTING";
export const FETCH_SETTINGS_SUCCESS = "FETCH_SETTINGS_SUCCESS";
export const FETCH_SETTINGS_ERRORS = "FETCH_SETTINGS_ERROR";
export const UPDATE_SETTINGS_REQUESTING = "UPDATE_SETTINGS_REQUESTING";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_ERRORS = "UPDATE_SETTINGS_ERRORS";

