export const FETCH_PROFILE_USER_REQUEST = "FETCH_PROFILE_USER_REQUEST";
export const FETCH_PROFILE_USER_SUCCESS = "FETCH_PROFILE_USER_SUCCESS";
export const FETCH_PROFILE_USER_ERRORS = "FETCH_PROFILE_USER_ERRORS";

