
export const ACTION_USER_REQUESTING = 'ACTION_USER_REQUESTING';
export const ACTION_USER_SUCCESS = 'ACTION_USER_SUCCESS';
export const ACTION_USER_ERROR = 'ACTION_USER_ERROR';
export const SET_STATE_USER_DEFAULT = "SET_STATE_USER_DEFAULT";
