export const ADD_TAG_REQUEST = "ADD_TAG_REQUEST";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const REMOVE_TAG_REQUEST = "REMOVE_TAG_REQUEST";
export const REMOVE_TAG_SUCCESS = "REMOVE_TAG_SUCCESS";

export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_ERRORS = "ADD_ARTICLE_ERRORS";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_ERRORS = "EDIT_ARTICLE_ERRORS";

