
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_ERRORS = "ADD_ARTICLE_ERRORS";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_ERRORS = "EDIT_ARTICLE_ERRORS";

export const SET_STATE_PUBLISH_DEFAULT = "SET_STATE_PUBLISH_DEFAULT";



