export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_ERRORS = "FETCH_COMMENTS_ERRORS";
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERRORS = "ADD_COMMENT_ERRORS";
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
