export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";
export const LIKE_ARTICLE_ERRORS = "LIKE_ARTICLE_ERRORS";
export const REMOVE_LIKE_ARTICLE_SUCCESS = "REMOVE_LIKE_ARTICLE_SUCCESS";
export const REMOVE_LIKE_ARTICLE_ERRORS = "REMOVE_LIKE_ARTICLE_ERRORS";
export const FAVORITE_ARTICLE_REQUEST = "FAVORITE_ARTICLE_REQUEST";