export const FAVORITE_ARTICLE_SUCCESS = "FAVORITE_ARTICLE_SUCCESS";
export const FAVORITE_ARTICLE_ERRORS = "FAVORITE_ARTICLE_ERRORS";
export const REMOVE_FAVORITE_ARTICLE_SUCCESS = "REMOVE_FAVORITE_ARTICLE_SUCCESS";
export const REMOVE_FAVORITE_ARTICLE_ERRORS = "REMOVE_FAVORITE_ARTICLE_ERRORS";
export const FAVORITE_ARTICLE_REQUEST = "FAVORITE_ARTICLE_REQUEST";
